### Python 基础算法练习（Hadoop + Spark + MySQL + Python）
## <center>1 >>> 数据结构+基本算法：python 顺序存储 vs 链式存储</center>
### <center>算法验证：张君颖  ； 报告日期：2021.1.20</center>
  <font color=blue><center>作者邮箱：zhang.jun.ying@outlook.com</center></font>   
  
  <font color=blue><center>项目源代码、数据、自定义函数已上传GitHub：</center></font>   
    
<font color=blue><center>https://github.com/lotbear/Python-Financial-investment-strategy</center></font>

### >>> 数据结构的组成方式   

1） 线性结构 ： 数组 、 链表 、 栈 、 队列 、 哈希表   

2） 树结构 ： 二叉树 、 二叉堆   

3） 图 ： 多对多的关联关系   

4） 其他结构 ： 由基本数据结构变形而来的 跳表 、 哈希链表 、 位图 等   

### >>> 算法选择不同数据结构，解决不同问题

1） 运算 ： 求最大公约数，超大整数和   

2） 查找 ： 在数据库中执行 SQL 语句  

3） 排序 ： 冒泡排序 、 快速排序 、 堆排序 、 计数排序 、 桶排序   

4） 最优决策 ： A星寻路算法 、 动态规划算法  

### >>> 算法的好坏  :  时间复杂度

基本操作的执行次数 T ( n ) : 常数 3 < 对数 3 log n < 线性 3 n < 多项式 3 n^2 + 3 n

对应的时间复杂度 O ( f ( n ) ) : 1 < log n < n < n^2

In [1]:
# 时间复杂度 T (n) = 3 ; O( 1 ) 顺序执行
def eat1(n):
    print("等待1min")
    print("等待1min")
    print("吃1cm面包")

In [2]:
eat1(3)

等待1min
等待1min
吃1cm面包


In [3]:
# 时间复杂度 T（n）= 3 log n ; O( log n ) while 判断执行
def eat2(n):
    while n > 1:
        print("等待1min")
        print("等待1min")
        print("吃 1/2 面包")
        n /= 2

In [4]:
eat2(3)

等待1min
等待1min
吃 1/2 面包
等待1min
等待1min
吃 1/2 面包


In [5]:
# 时间复杂度 T（n）= 3 n ; O( n ) for in 单循环
def eat3(n):
    for i in range(n):
        print("等待1min")
        print("等待1min")
        print("吃1cm面包")

In [6]:
eat3(3)

等待1min
等待1min
吃1cm面包
等待1min
等待1min
吃1cm面包
等待1min
等待1min
吃1cm面包


In [7]:
# 时间复杂度 T（n）= 3 n^2 + 3 n ; O( n^2 ) for in 双循环
def eat4(n):
    for i in range(n):
        for j in range(i):
            print("等待1min")
            print("等待1min")
            print("等待1min")
            print("等待1min")
            print("等待1min")
            print("等待1min")
        print("吃1cm面包")

In [8]:
for i in range(3):
    print(i)

0
1
2


In [9]:
eat4(3)

吃1cm面包
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
吃1cm面包
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
等待1min
吃1cm面包


### >>> 算法的好坏  :  空间复杂度

算法占用的临时内存空间 S ( n ) :  常数 3 < 线性 3 n < 幂次方 3 n^2  

对应的空间复杂度 O ( f ( n ) ) : 1 < n < n^2

In [10]:
# 空间复杂度 S（n）=  3 ; O( 1 ) 常量空间
def fun1(n):
    i = 1
    j = 2
    k = 3
    print(i,j,k)

In [11]:
fun1(3)

1 2 3


In [12]:
# 空间复杂度 S（n）= 3 n ; O( n ) 线性空间
def fun2(n):
    array1 = [[1]*n]
    array2 = [[2]*n]
    array3 = [[3]*n]
    print(array1,array2,array3)

In [13]:
fun2(3)

[[1, 1, 1]] [[2, 2, 2]] [[3, 3, 3]]


In [14]:
# 空间复杂度 S（n）= 3 n^2 ; O( n^2 ) 二维空间
def fun3(n):
    matrix1 = [[1]*n]*n
    matrix2 = [[2]*n]*n
    matrix3 = [[3]*n]*n
    print(matrix1)
    print(matrix2)
    print(matrix3)

In [15]:
fun3(3)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[2, 2, 2], [2, 2, 2], [2, 2, 2]]
[[3, 3, 3], [3, 3, 3], [3, 3, 3]]


递归空间： 函数调用栈  

当函数不断调用本身运算时，将调用的函数和参数信息压入栈中；   

当函数返回值后，执行出栈操作，调用的函数和参数信息从栈中弹出。

In [16]:
# 空间复杂度 S（n）= n ; O( n ) 递归空间
def fun4(n):
    if n > 0:
        matrix = [[1]*n]*n
        print(matrix)
        print('函数调用一次')
        fun4(n-1)

In [17]:
fun4(3)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
函数调用一次
[[1, 1], [1, 1]]
函数调用一次
[[1]]
函数调用一次


### >>> 数组 list / tuple / array / ndarray / series / DataFrame
由于数组元素是紧密存储在内存的，因此拥有高效的随机访问能力，只要给出下标 ，就可以用常量时间找到对应的元素。   

查找+更新数据，时间复杂度为 O(1)；插入+删除数据，时间复杂度为 O(n)  

List [ ]

In [18]:
list1=[1,2,'lotbear',4,5.5]
print(list1[2])
print(list1[2][4])
print(type(list1))

lotbear
e
<class 'list'>


tuple ( )

In [19]:
tuple1=(1,2,'2020-01-21',4,5*2)
print(tuple1[2])
print(tuple1[4])
print(type(tuple1))

2020-01-21
10
<class 'tuple'>


<font color=red>查看 numpy 的数组操作 ：ndarray</font>

In [20]:
import numpy as np

a=np.arange(10)
print(a)
print(type(a))
a[2]

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


2

In [21]:
b=np.array([1,2,'lotbear',4.8,5*5])
print(b)
print(type(b))
b[2]

['1' '2' 'lotbear' '4.8' '25']
<class 'numpy.ndarray'>


'lotbear'

In [22]:
c=np.random.randn(2,4)+3  # randn 为（0,1）正态分布
print(c)
print(type(c))
c[:,1]

[[2.45231065 4.65022315 3.11417536 3.33873916]
 [1.2633383  1.87332936 2.55891245 1.73028932]]
<class 'numpy.ndarray'>


array([4.65022315, 1.87332936])

In [23]:
d=np.zeros_like(c)
print(d)
print(type(d))
d[1][1]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


0.0

<font color=red>查看 pandas 的数组 array / series / DataFrame 的操作</font>

In [24]:
import pandas as pd

a=pd.array([1,2.2,3,'lotbear',5*5])
print(a)
print(type(a))

<PandasArray>
['1', '2.2', '3', 'lotbear', '25']
Length: 5, dtype: str1024
<class 'pandas.core.arrays.numpy_.PandasArray'>


In [25]:
b=pd.DataFrame({'column1':np.arange(5),
                'column2':np.ones(5),
                'column3':np.random.randint(2,9,5), # (low,high,num)
                'column4':['a','b','c','d','e']})
b

column1  column2  column3 column4
0        0      1.0        3       a
1        1      1.0        5       b
2        2      1.0        2       c
3        3      1.0        3       d
4        4      1.0        5       e

In [26]:
print(b['column1'])
print(type(b['column1']))
b['column1'][3]

0    0
1    1
2    2
3    3
4    4
Name: column1, dtype: int32
<class 'pandas.core.series.Series'>


3

In [27]:
b.loc[b.column3 > 3]

column1  column2  column3 column4
1        1      1.0        5       b
4        4      1.0        5       e

In [28]:
b.iloc[1,2]

5

In [29]:
b.iloc[[1,2]]

column1  column2  column3 column4
1        1      1.0        5       b
2        2      1.0        2       c

<font color=red>numpy 和 pandas 之间的数据结构转换</font>

In [30]:
c=np.array(b['column2'])
print(c)
print(type(c))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [31]:
d=pd.DataFrame(c)
print(d)
print(type(d))

     0
0  1.0
1  1.0
2  1.0
3  1.0
4  1.0
<class 'pandas.core.frame.DataFrame'>


### 数组插入元素

尾部插入 append  

中间插入 insert  

超范围插入

In [32]:
a=[1,2,3,4,5]
print('插入前：',a)
a.append('lotbear')
print('插入后：',a)
a.remove('lotbear')

插入前： [1, 2, 3, 4, 5]
插入后： [1, 2, 3, 4, 5, 'lotbear']


In [33]:
a.insert(2,'lotbear')
print('中间插入:',a)
a.remove('lotbear')

中间插入: [1, 2, 'lotbear', 3, 4, 5]


In [34]:
for i in range(5,1,-1):
    print(i)

5
4
3
2


### 自定义一个数组类 MyArray，实现元素插入 & 删除功能
  
数组适合读取和查询，但在插入 / 删除场景中并没有优势 ——> 引出 链表数据结构

In [35]:
class MyArray:
    def __init__(self,capacity):
        self.array=[None]*capacity
        self.size=capacity
    
    def insert(self,index,element):
        if index < 0 or index >= self.size:
            raise Exception('超出数组元素数量范围！')
        if self.size >= len(self.array):
            self.resize()
        # 从右往左循环，逐个元素向右移一位
        for i in range(self.size-1,-1,-1):
            self.array[i+1]=self.array[i]
        self.array[index]=element
        self.size +=1
    
    def resize(self):
        array_new=[None]*len(self.array)*2
        # 从旧数组复制到新数组
        for i in range(self.size):
            array_new[i]=self.array[i]
        self.array=array_new
        
    def output(self):
        for i in range(self.size):
            print(self.array[i])
            
    def remove(self,index):
        if index < 0 or index >= self.size:
            raise Exception('超出数组元素数量范围！')
        for i in range(index,self.size):
            self.array[i]=self.array[i+1]
        self.size -= 1

In [36]:
array = MyArray(6)
print('初始size:',array.size)
array.insert(2,9)
array.insert(2,8)
array.insert(2,7)
print('更新size:',array.size)
array.output()

初始size: 6
更新size: 9
None
None
7
8
9
None
None
None
None


In [37]:
array.remove(3)
array.output()

None
None
7
9
None
None
None
None


### >>> 链表 linked list  （适合增删数据，随机存储）
链表是一种在物理上非连续、非顺序的数据结构，由若干节点组成，<font color=red>存储方式为随机存储</font>   

单向链表：每个节点含存放的数据data + 指向下一个节点的指针   

双向链表：每个节点含存放的数据data + 前向 prev 指针 + 后向 next 指针 

In [38]:
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        self.prev = None

由于链表不能向数组一样通过下标快速定位，只能从头节点开始向后一个个节点逐一查找    

查找数据，时间复杂度最坏为 O( n ) ; 更新 / 插入 / 删除数据，时间复杂度为 O(1)  

In [39]:
class LinkedList:
    def __init__(self):
        self.size=0
        self.head=None
        self.last=None
    
    def get(self,index):
        if index < 0 or index >= self.size:
            raise Exception('超出链表节点范围！')
        p=self.head
        for i in range(index):
            p=p.next
        print('get p=p.next:',p)
        return p
    
    def insert(self,data,index):
        if index < 0 or index > self.size:
            raise Exception('超出链表节点范围！')
        node=Node(data)
        if self.size==0:
            # 空链表
            self.head=node
        elif index==0:
            # 插入头部
            node.next=self.head
            self.head=node
        elif self.size==index:
            # 插入尾部
            # self.last.next=node
            self.last=node;
        else:
            # 插入中间
            prev_node=self.get(index-1)
            node.next=prev_node.next
            prev_node.next=node
        self.size +=1
    
    def remove(self,index):
        if index < 0 or index >= self.size:
            raise Exception('超出链表节点范围！')
        # 暂存被删除的节点，用于返回
        if index==0:
            # 删除头节点
            removed_node=self.head
            self.head=self.head.next
        elif index == self.size-1:
            # 删除尾节点
            prev_node=self.get(index-1)
            removed_node=prev_node.next
            prev_node.next=None
            self.last=prev_node
        else:
            # 删除中间节点
            prev_node=self.get(index-1)
            next_node=prev_node.next.next
            removed_node=prev_node.next
            prev_node.next=next_node
            self.size -= 1
            return removed_node
    
    def output(self):
        p=self.head
        while p is not None:
            print(p.data)
            p=p.next

In [40]:
linkedList=LinkedList()
linkedList.insert(3,0)
linkedList.output()
print('='*30)
linkedList.insert(4,0)
linkedList.output()
print('='*30)
linkedList.insert(9,1)
linkedList.output()
print('='*30)
linkedList.insert(5,3)
linkedList.output()
print('='*30)
linkedList.insert(6,1)
print('整体插入数据后：')
linkedList.output()
linkedList.remove(1)
print('删除数据后：')
linkedList.output()

3
4
3
get p=p.next: <__main__.Node object at 0x000001E017848828>
4
9
3
4
9
3
get p=p.next: <__main__.Node object at 0x000001E017848828>
整体插入数据后：
4
6
9
3
get p=p.next: <__main__.Node object at 0x000001E017848828>
删除数据后：
4
9
3


### >>> python 中 collection.deque 双边队列（具有队列和栈的性质）

官方文档：https://docs.python.org/2/library/collections.html#collections.deque

In [41]:
from collections import deque 

a=deque('1234567')
print(a)
a.insert(0,'lotbear')
print(a)

deque(['1', '2', '3', '4', '5', '6', '7'])
deque(['lotbear', '1', '2', '3', '4', '5', '6', '7'])


In [42]:
a.pop()

'7'

In [43]:
a.rotate(2) # 链表向右循环前进 2步
print(a)

deque(['5', '6', 'lotbear', '1', '2', '3', '4'])


In [44]:
a.rotate(-3) # 链表向左循环前进 3步
print(a)

deque(['1', '2', '3', '4', '5', '6', 'lotbear'])


In [45]:
# 查看数据是否存在
print('2' in a)
print('7' in a)

True
False


In [46]:
# 指定空间查找数据位置
# D.index(value, [start, [stop]])
a.index('lotbear',0,7)

6

In [47]:
a.count('3') # 数值出现过几次

1